### ISSUE TITLE
Remove this repo from search results

### ISSUE THREAD

**Issue by craigbox** [helm/charts-classic#102]
There are still occasions where this repo shows up at the top of Google search results (e.g. for "cassandra helm").

Would it be worth marking it as not to be archived, by [renaming the master branch](https://webapps.stackexchange.com/questions/67344/how-to-prevent-a-public-github-repository-from-showing-up-on-search-results)?

**Comment by scottrigby** [comment]
This repo is now being "archived" in GitHub, hopefully that will help. If not, please reopen this issue in https://github.com/helm/community.
