### ISSUE TITLE
Define minimum viable chart requirements

### ISSUE THREAD

**Issue by sgoings** [helm/charts-classic#22]
There are useful charts... and there are not-so-useful charts. I would like to start the conversation about what makes an awesome chart and create a standard of quality within the deis/charts repo.

One thing that has been discussed thus far:
- all charts need to have service, replication controller, and pod definitions in the chart... unless it doesn't make sense to do so. Deploying a Jenkins master into a kubernetes cluster isn't so useful unless it has all three (rc, pod, service).

**Comment by technosophos** [comment]
I agree. I like the idea of having a "Helm Guide to Building Awesome Charts" document that would walk through the basics, including how to label, what parts we expect, and so on.

**Comment by bacongobbler** [comment]
+1. A "best practices" doc showing off some great examples like redis-standalone vs redis-cluster, example-todo etc. would be a great way to start a conversation on what makes a great chart.
