### ISSUE TITLE
Break apart selenium chart

### ISSUE THREAD

**Issue by sgoings** [helm/charts-classic#54]
Right now the selenium chart installs the hub as well as the chrome + firefox selenium nodes. Ideally if you're using selenium you'd want to control these or configure these separately, right? It makes sense to me to have a "selenium-hub" chart as well as a "selenium-node" chart. Thoughts @elsonrodriguez?

**Comment by elsonrodriguez** [comment]
What do you think of having a "selenium" meta chart that depends on "selenium-node*" and "selenium-hub"?

This way people can uninstall/upgrade components while still preserving the convenience of a one-command install.

(haven't done a feasibility check on this)

**Comment by technosophos** [comment]
With Helm 0.3.0, the meta chart idea would work well. I'd be happy to see us go this route.
