### ISSUE TITLE
Fix riak chart or remove it

### ISSUE THREAD

**Issue by mboersma** [helm/charts-classic#68]
The Docker image referenced in the riak chart is currently broken--see deis/riak#28. This prevents `helm` chart testing from completing in CI.

**Comment by bacongobbler** [comment]
If we decide by EOD that we're abandoning the project then we should probably remove it.

**Comment by sgoings** [comment]
@bacongobbler... edit for clarity: "if we choose not to use Riak then we should probably remove the chart" (reduces the impact of what "abandoning the project" refers to :smile:).
