### ISSUE TITLE
make a subfolder for the charts

### ISSUE THREAD

**Issue by rimusz** [helm/charts-classic#9]
Shall we make e.g. `library` folder and put charts there, as soon we have many charts, this repo will be come unreadable/messy

**Comment by sgoings** [comment]
Agreed. See Homebrew's situation with limits of GitHub here: https://github.com/Homebrew/homebrew/tree/master/Library/Formula

**Comment by evanphx** [comment]
breaking it out as `file.Join(name[:2],name)` is a quite robust solution that keeps things well distributed even for a very large number of charts.

**Comment by rimusz** [comment]
no relevant anymore, closing it
