### ISSUE TITLE
Attemping to regenerate manifests

### ISSUE THREAD

**Issue by andrewho83** [helm/charts-classic#97]
I have both `2.2.0` and `2.3.0` charts and am attempting to generate the manifests via:

`helmc generate -x -f manifests workflow-v2.3.0`

and this results in the following:

`[ERROR] Failed to complete generation: lstat /Users/<username>/.helmc/workspace/charts/manifests: no such file or directory`

Under the `.helmc` directory, I have the following dir structure: 

`~/.helmc/workspace/charts/workflow-v2.2.0`
`~/.helmc/workspace/charts/workflow-v2.3.0`

I'm guessing the error above only case-d in for a single version?

**Comment by mboersma** [comment]
I think `helmc` is confused by the ordering of the command-line flags. `-x` actually takes `manifests` as an argument. Does this work for you?

```
helmc generate -x manifests -f workflow-v2.3.0
```
